Dizimo/Controllers/DizimistaController.cs
using Dizimo.Filters;
using Dizimo.Models;
using Dizimo.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Dizimo.Controllers
{
    [PaginaparaUsuarioLogado]
    public class DizimistaController : Controller
    {
        private readonly IDizimistaRepositorio _dizimistaRepositorio;
        public DizimistaController(IDizimistaRepositorio dizimistaRepositorio)
        {
            _dizimistaRepositorio = dizimistaRepositorio;
        }
        public IActionResult Index()
        {
            List<DizimistaModel> dizimistas = _dizimistaRepositorio.DizimistaBuscarTodos();
            return View(dizimistas);
        }
        public IActionResult DizimistaCriar()
        {
            return View();
        }
        public IActionResult DizimistaEditar(int id)
        {
            DizimistaModel dizimista = _dizimistaRepositorio.DizimistaListarPorId(id);
            return View(dizimista);
        }
        public IActionResult DizimistaApagarConfirmacao(int id)
        {
            DizimistaModel dizimista = _dizimistaRepositorio.DizimistaListarPorId(id);
            return View(dizimista);
        }

        public IActionResult DizimistaApagar(int id)
        {
            try
            {
                bool apagado = _dizimistaRepositorio.DizimistaApagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Dizimista Apagada com sucesso.";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos apagar o cadastro.";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar o cadastro, mais detalhes do erro: {erro.Message}.";
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public IActionResult DizimistaCriar(DizimistaModel dizimista)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _dizimistaRepositorio.DizimistaAdicionar(dizimista);
                    TempData["MensagemSucesso"] = "Cadastrado efetuado com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(dizimista);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos realizar o cadastro, tente novamente, detalhe do erro: {erro.Message}.";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult DizimistaEditar(DizimistaModel dizimista)
        {
            _dizimistaRepositorio.DizimistaAtualizar(dizimista);
            TempData["MensagemSucesso"] = "Dizimista Alterado com sucesso.";
            return RedirectToAction("index");
        }
    }
}

Dizimo/Views/Dizimista/DizimistaApagarConfirmacao.cshtml
@model DizimistaModel
@{
    ViewData["Title"] = "Confirmação apagar cadastro";
}

<div class="text-center p-3">
    <h3>Realmente deseja apagar o cadastro (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary d-block" role="button" asp-controller="Dizimista" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger d-block" role="button" asp-controller="Dizimista" asp-action="DizimistaApagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

Dizimo/Views/Dizimista/DizimistaCriar.cshtml
@using Dizimo.Enums;
@model DizimistaModel

@{
    ViewData["Title"] = "Novo Cadastro";
}

<div class="text-center p-3">
    
    <h1 class="display-4">Cadastrar Dizimistas</h1>

</div>


<form asp-controller="Dizimista" asp-action="DizimistaCriar" method="post">
    
    <div class="form-row row mb-3">
        <div class="form-group col-sm-6">
            <label for="Nome" class="form-label"></label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Nome Completo" />
            @Html.ValidationMessageFor(x => x.Nome)
        </div>
        <div class="form-group col-sm-2">
            <label for="DataNascimento" class="form-label"></label>
            <input type="date" asp-for="DataNascimento" class="form-control" />
            @Html.ValidationMessageFor(x => x.DataNascimento)
        </div>
        <div class="form-group col-sm-4">
            <label for="CpfCnpj" class="form-label"></label>
            <input asp-for="CpfCnpj" class="form-control" placeholder="Documento (CPF/CNPJ)" />
            @Html.ValidationMessageFor(x => x.CpfCnpj)
        </div>
    </div>

    <div class="form-row row mb-3">
        <div class="form-group col-sm-6">
            <label for="Email" class="form-label"></label>
            <input asp-for="Email" class="form-control" placeholder="Email" />
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div class="form-group col-sm-3">
            <label for="Fone" class="form-label"></label>
            <input asp-for="Fone" class="form-control" placeholder="Telefone" />
            @Html.ValidationMessageFor(x => x.Fone)
        </div>
    </div>

    <div class="form-row row mb-3">
        <div class="form-group col-sm-2">
            <label for="CEP" class="form-label"></label>
            <input asp-for="CEP" class="form-control" placeholder="CEP" />
            @Html.ValidationMessageFor(x => x.CEP)
        </div>
        <div class="form-group col-sm-6">
            <label for="Endereco" class="form-label"></label>
            <input asp-for="Endereco" class="form-control" placeholder="Endereço" />
            @Html.ValidationMessageFor(x => x.Endereco)
        </div>
        <div class="form-group col-sm-4">
            <label for="Complemento" class="form-label"></label>
            <input asp-for="Complemento" class="form-control" placeholder="Complemento Apto, casa...." />
            @Html.ValidationMessageFor(x => x.Complemento)
        </div>

        <div class="form-row row mb-3">
            <div class="form-group col-sm-4">
                <label for="Cidade" class="form-label"></label>
                <input asp-for="Cidade" class="form-control" placeholder="Cidade" />
                @Html.ValidationMessageFor(x => x.Cidade)
            </div>
            <div class="form-group col-sm-2">
                <label for="UF" class="form-label"></label>
                <input asp-for="UF" class="form-control" placeholder="Estado" />
                @Html.ValidationMessageFor(x => x.UF)
            </div>
        </div>

        <div class="form-group p-2">
            <div class="row text-center">
                <div class="form-group col-sm-4 col-md-4 col-lg-4">
                    <input type="submit" asp-controller="Dizimista" value="Salvar" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-sm-4 col-md-4 col-lg-4">
                    <a asp-controller="Dizimista" asp-action="Index" class="btn btn-secondary btn-block">
                        <i class="fa fa-table"></i>Voltar
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</form>

Dizimo/Views/Dizimista/DizimistaEditar.cshtml
@using Dizimo.Enums;
@model DizimistaModel

@{
    ViewData["Title"] = "Editar Cadastro";
}

<div class="text-center p-3">
    
    <h1 class="display-4">Editar Dizimistas</h1>

</div>


<form asp-controller="Dizimista" asp-action="DizimistaEditar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-row row mb-3">
        <div class="form-group col-sm-6">
            <label for="Nome" class="form-label"></label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Nome Completo" />
            @Html.ValidationMessageFor(x => x.Nome)
        </div>
        <div class="form-group col-sm-2">
            <label for="DataNascimento" class="form-label"></label>
            <input type="date" asp-for="DataNascimento" class="form-control" />
            @Html.ValidationMessageFor(x => x.DataNascimento)
        </div>
        <div class="form-group col-sm-4">
            <label for="CpfCnpj" class="form-label"></label>
            <input asp-for="CpfCnpj" class="form-control" placeholder="Documento (CPF/CNPJ)" />
            @Html.ValidationMessageFor(x => x.CpfCnpj)
        </div>
    </div>

    <div class="form-row row mb-3">
        <div class="form-group col-sm-6">
            <label for="Email" class="form-label"></label>
            <input asp-for="Email" class="form-control" placeholder="Email" />
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div class="form-group col-sm-3">
            <label for="Fone" class="form-label"></label>
            <input asp-for="Fone" class="form-control" placeholder="Telefone" />
            @Html.ValidationMessageFor(x => x.Fone)
        </div>
    </div>

    <div class="form-row row mb-3">
        <div class="form-group col-sm-2">
            <label for="CEP" class="form-label"></label>
            <input asp-for="CEP" class="form-control" placeholder="CEP" />
            @Html.ValidationMessageFor(x => x.CEP)
        </div>
        <div class="form-group col-sm-6">
            <label for="Endereco" class="form-label"></label>
            <input asp-for="Endereco" class="form-control" placeholder="Endereço" />
            @Html.ValidationMessageFor(x => x.Endereco)
        </div>
        <div class="form-group col-sm-4">
            <label for="Complemento" class="form-label"></label>
            <input asp-for="Complemento" class="form-control" placeholder="Complemento Apto, casa...." />
            @Html.ValidationMessageFor(x => x.Complemento)
        </div>

        <div class="form-row row mb-3">
            <div class="form-group col-sm-4">
                <label for="Cidade" class="form-label"></label>
                <input asp-for="Cidade" class="form-control" placeholder="Cidade" />
                @Html.ValidationMessageFor(x => x.Cidade)
            </div>
            <div class="form-group col-sm-2">
                <label for="UF" class="form-label"></label>
                <input asp-for="UF" class="form-control" placeholder="Estado" />
                @Html.ValidationMessageFor(x => x.UF)
            </div>
        </div>

        <div class="form-group p-2">
            <div class="row text-center">
                <div class="form-group col-sm-4 col-md-4 col-lg-4">
                    <input type="submit" asp-controller="Dizimista" value="Salvar" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-sm-4 col-md-4 col-lg-4">
                    <a asp-controller="Dizimista" asp-action="Index" class="btn btn-secondary btn-block">
                        <i class="fa fa-table"></i>Voltar
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

Dizimo/Views/Dizimista/Index.cshtml
@model List<DizimistaModel>

@{
    ViewData["Title"] = "Listagem de dizimistas";
}


<div class="text-center p-3">
   
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Dizimista" asp-action="DizimistaCriar">Criar novo cadastro</a>
    </div>
    <br />

    <h1 class="display-4">Listagem de dizimistas</h1>

    <table class="table" id="table-dizimistas">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Data Nascimento</th>
                <th scope="col">Telefone</th>
                <th scope="col"></th>
            </tr>
        </thead>
        
        <tbody>
           @if (Model != null && Model.Any())
                {
                    {
                        @foreach (DizimistaModel dizimista in Model)
                        {
                            <tr>
                            <th scope="row">@dizimista.Id</th>
                            <td>@dizimista.Nome</td>
                            <td>@dizimista.DataNascimento</td>
                            <td>@dizimista.Fone</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a role="button" class="btn btn-primary" asp-route-id="@dizimista.Id" asp-controller="Dizimista" asp-action="DizimistaEditar">Editar</a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@dizimista.Id" asp-controller="Dizimista" asp-action="DizimistaApagarConfirmacao">Apagar</a>
                                </div>
                            </td>
                            </tr>
                        }
                    }
                }
                else
                {
                    <tr class="odd"><td valign="top" colspan="5">Nenhum cadastro encontrado</td></tr>
                }
        </tbody>
    </table>

</div>