Dizimo/Controllers/ControlePagamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dizimo.Data;
using Dizimo.Models;
using Dizimo.Repositorio;

#nullable disable

namespace Dizimo.Controllers
{
    public class ControlePagamentoController : Controller
    {
        private readonly BancoContext _bancoContext;
        private readonly IControlePagamentoRepositorio _controlePagamentoRepositorio;
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IDizimistaRepositorio _dizimistaRepositorio;

        public ControlePagamentoController(IUsuarioRepositorio usuarioRepositorio, 
                                           IDizimistaRepositorio dizimistaRepositorio,
                                           IControlePagamentoRepositorio controlePagamentoRepositorio,
                                           BancoContext context)
        {
            _bancoContext = context;
            _usuarioRepositorio = usuarioRepositorio;
            _dizimistaRepositorio = dizimistaRepositorio;
            _controlePagamentoRepositorio = controlePagamentoRepositorio;
        }

        // GET: ControlePagamento
        public async Task<IActionResult> Index()
        {
            List<ControlePagamentoModel> controlePagamentos = _controlePagamentoRepositorio.BuscarCPTodos();
            return View(controlePagamentos);

            //return _bancoContext.ControlePagamentos != null ? 
            //              View(await _bancoContext.ControlePagamentos.ToListAsync()) :
            //              Problem("Entity set 'BancoContext.ControlePagamentos'  is null.");
        }

        // GET: ControlePagamento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _bancoContext.ControlePagamentos == null)
            {
                return NotFound();
            }

            var controlePagamentoModel = await _bancoContext.ControlePagamentos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (controlePagamentoModel == null)
            {
                return NotFound();
            }

            return View(controlePagamentoModel);
        }

        // GET: ControlePagamento/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ControlePagamento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DizimistaId,ComunidadeId,UsuarioID,MesAno,Janeiro,Fevereiro,Marco,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro,Atualizacao")] ControlePagamentoModel controlePagamentoModel)
        {
            if (ModelState.IsValid)
            {
                _bancoContext.Add(controlePagamentoModel);
                await _bancoContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(controlePagamentoModel);
        }

        public IControlePagamentoRepositorio Get_controlePagamentoRepositorio()
        {
            return _controlePagamentoRepositorio;
        }

        // GET: ControlePagamento/Edit/5
        public IActionResult Edit(int id)
        {
            ControlePagamentoModel controlePagamento = new ControlePagamentoModel();
            controlePagamento = _controlePagamentoRepositorio.ListarCPPorId(id);
            controlePagamento.ListaPagamentoComunidades = _bancoContext.Comunidades.ToList();
            return View(controlePagamento);
        }

        // POST: ControlePagamento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DizimistaId,ComunidadeId,UsuarioID,MesAno,Janeiro,Fevereiro,Marco,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro,Atualizacao")] ControlePagamentoModel controlePagamentoModel)
        {
            if (id != controlePagamentoModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bancoContext.Update(controlePagamentoModel);
                    await _bancoContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ControlePagamentoModelExists(controlePagamentoModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(controlePagamentoModel);
        }

        // GET: ControlePagamento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _bancoContext.ControlePagamentos == null)
            {
                return NotFound();
            }

            var controlePagamentoModel = await _bancoContext.ControlePagamentos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (controlePagamentoModel == null)
            {
                return NotFound();
            }

            return View(controlePagamentoModel);
        }

        // POST: ControlePagamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_bancoContext.ControlePagamentos == null)
            {
                return Problem("Entity set 'BancoContext.ControlePagamentos'  is null.");
            }
            var controlePagamentoModel = await _bancoContext.ControlePagamentos.FindAsync(id);
            if (controlePagamentoModel != null)
            {
                _bancoContext.ControlePagamentos.Remove(controlePagamentoModel);
            }
            
            await _bancoContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ControlePagamentoModelExists(int id)
        {
          return (_bancoContext.ControlePagamentos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Dizimo/Views/ControlePagamento/Create.cshtml
@model Dizimo.Models.ControlePagamentoModel

@{
    ViewData["Title"] = "Incluir Dízimo";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Dízimo</h1>

</div>



@*original a partir de aqui*@
<div class="row p-3">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DizimistaId" class="control-label"></label>
                <input asp-for="DizimistaId" class="form-control" />
                <span asp-validation-for="DizimistaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComunidadeId" class="control-label"></label>
                <input asp-for="ComunidadeId" class="form-control" />
                <span asp-validation-for="ComunidadeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioID" class="control-label"></label>
                <input asp-for="UsuarioID" class="form-control" />
                <span asp-validation-for="UsuarioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MesAno" class="control-label"></label>
                <input asp-for="MesAno" class="form-control" />
                <span asp-validation-for="MesAno" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Janeiro" /> @Html.DisplayNameFor(model => model.Janeiro)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Fevereiro" /> @Html.DisplayNameFor(model => model.Fevereiro)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Marco" /> @Html.DisplayNameFor(model => model.Marco)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Abril" /> @Html.DisplayNameFor(model => model.Abril)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Maio" /> @Html.DisplayNameFor(model => model.Maio)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Junho" /> @Html.DisplayNameFor(model => model.Junho)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Julho" /> @Html.DisplayNameFor(model => model.Julho)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Agosto" /> @Html.DisplayNameFor(model => model.Agosto)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Setembro" /> @Html.DisplayNameFor(model => model.Setembro)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Outubro" /> @Html.DisplayNameFor(model => model.Outubro)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Novembro" /> @Html.DisplayNameFor(model => model.Novembro)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Dezembro" /> @Html.DisplayNameFor(model => model.Dezembro)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Atualizacao" class="control-label"></label>
                <input asp-for="Atualizacao" class="form-control" />
                <span asp-validation-for="Atualizacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dizimo/Views/ControlePagamento/Delete.cshtml
@model Dizimo.Models.ControlePagamentoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ControlePagamentoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DizimistaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DizimistaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComunidadeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComunidadeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsuarioID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsuarioID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MesAno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MesAno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Janeiro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Janeiro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fevereiro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fevereiro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abril)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abril)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Junho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Junho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Julho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Julho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agosto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agosto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Outubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Outubro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Novembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Novembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atualizacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atualizacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Dizimo/Views/ControlePagamento/Details.cshtml
@model Dizimo.Models.ControlePagamentoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ControlePagamentoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DizimistaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DizimistaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComunidadeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComunidadeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsuarioID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsuarioID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MesAno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MesAno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Janeiro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Janeiro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fevereiro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fevereiro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abril)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abril)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Junho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Junho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Julho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Julho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agosto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agosto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Outubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Outubro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Novembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Novembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezembro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atualizacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atualizacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Dizimo/Views/ControlePagamento/Index.cshtml
@using System.Globalization;
@*@model IEnumerable<Dizimo.Models.ControlePagamentoModel>*@
@model List<ControlePagamentoModel>

@{
    ViewData["Title"] = "Controle do dízimo";
}
<div class="text-center p-3">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="ControlePagamento" asp-action="Create">Lançamento do dízimo</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem do dízimo</h1>

    <table class="table" id="table-controlePagamento" style="width:100%">
        <thead>
            <tr>
                @*<th scope="col">#</th>*@
                <th scope="col">Dizimista</th>
                <th scope="col">Comunidade</th>
                <th scope="col">MesAno</th>
                <th scope="col">Atualizado em</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        @if (Model != null && Model.Any())
        {
                @foreach (ControlePagamentoModel controlePagamento in Model)
                {
                    <tr>
                        @*<th scope="row">@controlePagamento.Id</th>*@
                        <td>@controlePagamento.dizimistacp</td>
                        <td>@controlePagamento.comunidadecp</td>
                        <td>@controlePagamento.MesAno</td>

                        <td>
                            @controlePagamento.Atualizacao
                        </td>

                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@controlePagamento.Id" asp-controller="ControlePagamento" asp-action="Edit">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@controlePagamento.Id" asp-controller="ControlePagamento" asp-action="Delete">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
        }
        else
        {
            <tr class="odd"><td valign="top" colspan="5">Nenhum Lançamento encontrado</td></tr>
        }
        </tbody>
    </table>
</div>